[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
testtest = "CC3bHAaxZR4KCrNTbG9PqZDqckVQn7rzm6Bzir1yuRN2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=47fcd2c1-bfb0-4224-8257-ce200078152a"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
